dbt_airbnb:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      password: postgres
      port: 5432
      schema: airbnb
      threads: 1
      type: postgres
      user: postgres
  target: dev
